version: "3.4"
services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101315.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-geth.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    volumes:
      - ./envs/${NETWORK_NAME}/config:/chainconfig
      - ./scripts/:/scripts
      - shared:/shared
      - op_geth:/geth
    networks:
      - op-network
    ports:
      - ${PORT__OP_GETH_HTTP}:${PORT__OP_GETH_HTTP}
      - ${PORT__OP_GETH_WS}:${PORT__OP_GETH_WS}
      - ${PORT__OP_GETH_AUTH_RPC}:${PORT__OP_GETH_AUTH_RPC}
      - ${PORT__OP_GETH_P2P:-39393}:${PORT__OP_GETH_P2P:-39393}/udp
      - ${PORT__OP_GETH_P2P:-39393}:${PORT__OP_GETH_P2P:-39393}/tcp

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.7.7
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-node.sh
    env_file:
      - ./envs/${NETWORK_NAME}/op-node.env
      - .env
    volumes:
      - ./envs/${NETWORK_NAME}/config:/chainconfig
      - ./scripts/:/scripts
      - shared:/shared
    networks:
      - op-network
    ports:
      - ${PORT__OP_NODE_P2P}:${PORT__OP_NODE_P2P}/udp
      - ${PORT__OP_NODE_P2P}:${PORT__OP_NODE_P2P}/tcp
      - ${PORT__OP_NODE_HTTP}:${PORT__OP_NODE_HTTP}

volumes:
  geth:
  shared:
  op_geth:

networks:
  op-network:
